// 12 business-card variants for mutual™.
// Each variant = a theme. Cards share a common bilingual layout
// (Korean + English, vCard QR, ≥14pt body floor).

const cardholders = [
  {
    id: 'alex',
    name: 'Alex Jihoon Park',
    nameKo: '박지훈',
    title: 'Co-founder · Hardware',
    titleKo: '공동창업자 · 하드웨어',
    email: 'alex@mutual.solutions',
    linkedin: 'linkedin.com/in/alexjihoonpark',
    vcardN: 'Park%3BAlex%20Jihoon',
    vcardFN: 'Alex%20Jihoon%20Park',
    vcardTitle: 'Co-founder%20Hardware',
    vcardEmail: 'alex%40mutual.solutions',
  },
  {
    id: 'yejun',
    name: 'Yejun Jang',
    nameKo: '장예준',
    title: 'CEO · AI & Security',
    titleKo: '대표이사 · AI 보안',
    email: 'yejun@mutual.solutions',
    linkedin: 'linkedin.com/in/yejunjang',
    vcardN: 'Jang%3BYejun',
    vcardFN: 'Yejun%20Jang',
    vcardTitle: 'CEO%20AI%20%26%20Security',
    vcardEmail: 'yejun%40mutual.solutions',
  },
];

// theme keys:
//   bg, fg, fgDim, accent, accentSoft, paper (bool), grid (bool), wordmarkColor,
//   logoFile (logo-white | logo-teal | logo-dark | logo-amber | logo-mono | ...),
//   qrFg, qrBg (HEX without #),
//   font, mono (Google Fonts family names),
//   tag (one-line description shown in gallery)
const variants = [
  {
    id: 'tech', name: 'Lab', sub: 'dark · cyan · signed-at-source',
    tag: 'TECH · 기술 / 다크',
    bg: '#0f172a', bgGrad: 'linear-gradient(135deg,#0f172a 0%, #1e293b 100%)',
    fg: '#ffffff', fgDim: '#94a3b8', accent: '#22d3ee', accentSoft: '#4a8b9c',
    paper: false, grid: true, wordmarkColor: '#ffffff',
    logoFile: 'logo-white.svg',
    qrFg: '0f172a', qrBg: 'ffffff',
    font: 'Inter', mono: 'JetBrains+Mono',
  },
  {
    id: 'paper', name: 'Press', sub: 'warm cream · Hangul-led',
    tag: 'PAPER · 종이 / 한글 우선',
    bg: '#f7f3ec', bgGrad: '#f7f3ec',
    fg: '#0f172a', fgDim: '#64748b', accent: '#4a8b9c', accentSoft: '#2a5561',
    paper: true, grid: false, wordmarkColor: '#0f172a',
    logoFile: 'logo-teal.svg',
    qrFg: '0f172a', qrBg: 'f7f3ec',
    font: 'Inter', mono: 'JetBrains+Mono',
  },
  {
    id: 'noir', name: 'Noir', sub: 'pitch black · electric cyan',
    tag: 'NOIR · 블랙 / 전기 시안',
    bg: '#000000', bgGrad: 'linear-gradient(180deg,#000 0%, #0a0a0a 100%)',
    fg: '#ffffff', fgDim: '#888', accent: '#22d3ee', accentSoft: '#0891b2',
    paper: false, grid: false, wordmarkColor: '#22d3ee',
    logoFile: 'logo-white.svg',
    qrFg: '000000', qrBg: 'ffffff',
    font: 'Inter', mono: 'JetBrains+Mono',
  },
  {
    id: 'exec', name: 'Counsel', sub: 'navy · gold · classic corporate',
    tag: 'EXEC · 네이비 / 금장',
    bg: '#fafaf7', bgGrad: '#fafaf7',
    fg: '#0a1f3d', fgDim: '#5b6478', accent: '#b08d3a', accentSoft: '#8b6f2c',
    paper: true, grid: false, wordmarkColor: '#0a1f3d',
    logoFile: 'logo-navy.svg',
    qrFg: '0a1f3d', qrBg: 'fafaf7',
    font: 'Inter', mono: 'JetBrains+Mono',
  },
  {
    id: 'mono', name: 'Achromat', sub: 'pure grayscale · no accent',
    tag: 'MONO · 흑백 / 미니멀',
    bg: '#ffffff', bgGrad: '#ffffff',
    fg: '#111111', fgDim: '#888', accent: '#111111', accentSoft: '#444',
    paper: false, grid: false, wordmarkColor: '#111111',
    logoFile: 'logo-black.svg',
    qrFg: '111111', qrBg: 'ffffff',
    font: 'Inter', mono: 'JetBrains+Mono',
  },
  {
    id: 'terminal', name: 'CRT', sub: 'green-on-black · monospace',
    tag: 'TERMINAL · 터미널 / 모노',
    bg: '#0a0d0a', bgGrad: 'radial-gradient(ellipse at center, #0a1410 0%, #050805 100%)',
    fg: '#22ff88', fgDim: '#0a8d4a', accent: '#22ff88', accentSoft: '#0a8d4a',
    paper: false, grid: true, wordmarkColor: '#22ff88',
    logoFile: 'logo-green.svg',
    qrFg: '22ff88', qrBg: '0a0d0a',
    font: 'JetBrains+Mono', mono: 'JetBrains+Mono',
  },
  {
    id: 'archive', name: 'Archive', sub: 'sepia · serif feel · vintage',
    tag: 'ARCHIVE · 아카이브 / 세피아',
    bg: '#ece4d2', bgGrad: '#ece4d2',
    fg: '#2c1d0a', fgDim: '#6b5236', accent: '#8b4513', accentSoft: '#a8682b',
    paper: true, grid: false, wordmarkColor: '#2c1d0a',
    logoFile: 'logo-sepia.svg',
    qrFg: '2c1d0a', qrBg: 'ece4d2',
    font: 'Inter', mono: 'JetBrains+Mono',
  },
  {
    id: 'neon', name: 'Vapor', sub: 'cyan→magenta gradient · synth',
    tag: 'NEON · 네온 / 그라디언트',
    bg: '#0d0a1f', bgGrad: 'linear-gradient(135deg,#0d0a1f 0%, #1a0f3a 60%, #2a0f4a 100%)',
    fg: '#ffffff', fgDim: '#a78bfa', accent: '#f0abfc', accentSoft: '#22d3ee',
    paper: false, grid: false, wordmarkColor: '#ffffff',
    logoFile: 'logo-magenta.svg',
    qrFg: 'ffffff', qrBg: '0d0a1f',
    font: 'Inter', mono: 'JetBrains+Mono',
  },
  {
    id: 'linen', name: 'Linen', sub: 'off-white · sage green · natural',
    tag: 'LINEN · 리넨 / 세이지',
    bg: '#f4f1ea', bgGrad: '#f4f1ea',
    fg: '#1f2a24', fgDim: '#718272', accent: '#5d7a5d', accentSoft: '#8aa68a',
    paper: true, grid: false, wordmarkColor: '#1f2a24',
    logoFile: 'logo-sage.svg',
    qrFg: '1f2a24', qrBg: 'f4f1ea',
    font: 'Inter', mono: 'JetBrains+Mono',
  },
  {
    id: 'duotone', name: 'Duotone', sub: 'half dark · half light split',
    tag: 'DUOTONE · 듀오톤 / 분할',
    bg: '#0f172a', bgGrad: 'linear-gradient(90deg,#0f172a 0%, #0f172a 50%, #f7f3ec 50%, #f7f3ec 100%)',
    fg: '#ffffff', fgDim: '#94a3b8', accent: '#22d3ee', accentSoft: '#4a8b9c',
    paper: false, grid: false, wordmarkColor: '#ffffff',
    logoFile: 'logo-white.svg',
    qrFg: '0f172a', qrBg: 'f7f3ec',
    font: 'Inter', mono: 'JetBrains+Mono',
    isDuotone: true,
  },
  {
    id: 'korean', name: 'Hangul', sub: '뮤추얼 wordmark · Korean primary',
    tag: 'KOREAN · 한글 우선 / 뮤추얼',
    bg: '#fffaf0', bgGrad: '#fffaf0',
    fg: '#1a1a1a', fgDim: '#666', accent: '#c4302b', accentSoft: '#8b1f1c',
    paper: true, grid: false, wordmarkColor: '#1a1a1a',
    logoFile: 'logo-red.svg',
    qrFg: '1a1a1a', qrBg: 'fffaf0',
    font: 'Inter', mono: 'JetBrains+Mono',
    isKorean: true,
  },
  {
    id: 'idcard', name: 'Clearance', sub: 'security badge · ID-grade',
    tag: 'ID-CARD · 보안 배지',
    bg: '#fafafa', bgGrad: '#fafafa',
    fg: '#1a1a1a', fgDim: '#666', accent: '#dc2626', accentSoft: '#7f1d1d',
    paper: false, grid: false, wordmarkColor: '#1a1a1a',
    logoFile: 'logo-red.svg',
    qrFg: '1a1a1a', qrBg: 'fafafa',
    font: 'Inter', mono: 'JetBrains+Mono',
    isIdCard: true,
  },
];

module.exports = { variants, cardholders };
